In [2]:
import numpy as np
print(numbered:= np.array(list(range(10)))) # список из 10 чисел от 0 до 9 в массив
print((zeros :=np.zeros((2,5))).dtype)
print((ones_arr := np.ones((5,4))).shape) 
print(numbered[2])
print(numbered[1:].reshape((3,3))) #меняю форму, срез нужен для изменения длинны
print(numbered*numbered) #поэлементное произведение массивов, в данном случае квадрат 
print(numbered.mean()) #среднее значение

[0 1 2 3 4 5 6 7 8 9]
float64
(5, 4)
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0  1  4  9 16 25 36 49 64 81]
4.5
